# 7Mail 临时邮箱系统
# 作者：傲始网络
# 官网：www.ao-s.cn
# 公众号：傲始网络

name = "7mail"
main = "worker/src/index.ts"

minify = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-27"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"
migrations_dir = "worker/drizzle"

[vars]
PASSWORD = "${PASSWORD}"
COOKIES_SECRET = "${COOKIES_SECRET}"
EMAIL_DOMAIN = "${EMAIL_DOMAIN}"
SEND_CHANNEL = "${SEND_CHANNEL}"
SENDER_EMAIL = "${SENDER_EMAIL}"
SEND_RATE_LIMIT_PER_MINUTE = "${SEND_RATE_LIMIT_PER_MINUTE}"
SEND_IP_RATE_LIMIT_PER_MINUTE = "${SEND_IP_RATE_LIMIT_PER_MINUTE}"
TURNSTILE_KEY = "${TURNSTILE_KEY}"
TURNSTILE_SECRET = "${TURNSTILE_SECRET}"
API_RATE_LIMIT_PER_MINUTE = "${API_RATE_LIMIT_PER_MINUTE}"
SHOW_AFF = "${SHOW_AFF}"
ENABLE_OPENAPI = "false"
MAILBOX_TOKEN_SECRET = "${MAILBOX_TOKEN_SECRET}"

GMAIL_ENABLED = "${GMAIL_ENABLED}"
GMAIL_ADDRESS = "${GMAIL_ADDRESS}"
GMAIL_SYNC_ADDRESS = "${GMAIL_SYNC_ADDRESS}"
GMAIL_CLIENT_ID = "${GMAIL_CLIENT_ID}"
GMAIL_CLIENT_SECRET = "${GMAIL_CLIENT_SECRET}"
GMAIL_REFRESH_TOKEN = "${GMAIL_REFRESH_TOKEN}"

[triggers]
crons = ["0 * * * *"]

[build]
command = "pnpm run build"

[assets]
binding = "ASSETS"
directory = "frontend/build/client"
